In [1]:
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import plot
from dtaidistance import dtw_ndim


data = pd.read_csv('data/metrics_results.csv')

for m in data.columns.drop(['algorithm', 'n_clusters']):
    df_test = data[['algorithm','n_clusters', m]]

    # transposing
    df_test_transposed = df_test.pivot_table(index='algorithm', columns=['n_clusters'], values=m).reset_index()
    df_test_final = df_test_transposed.rename_axis('').rename_axis("", axis="columns").set_index('algorithm')

    #df_test_final.T.plot(figsize=(20,10), title=ind)

df_test_final.head()
# plot(fig)

3         4         5         6         7  \
algorithm                                                                 
Hierarchical average   1.951416  0.478705  1.288793  0.673182  0.577952   
Hierarchical complete  0.538044  0.530005  0.415432  0.625359  0.444630   
Hierarchical single         NaN       NaN  0.510060       NaN       NaN   
KMeans                 0.471789  0.332931  0.339470  0.377618  0.401812   

                              8         9        10  
algorithm                                            
Hierarchical average   0.712849  0.712849  0.466507  
Hierarchical complete  0.460061  0.712849  0.498794  
Hierarchical single         NaN       NaN       NaN  
KMeans                 0.423789  0.379686  0.362581

In [2]:
# tuning for optimal k
# k_max = 10
# silhouette = []
# chscore = []
# dunnindex = []
# for k in range(2, k_max+1):
#     kmeans = kmeans_clustering(data, k)
#     silhouette.append(silhouette_score(dtw_matrix, kmeans.labels_))
#     chscore.append(symbolicDA.index_G1d(dtw_matrix, kmeans.labels_)[0])
#     dunnindex.append(clValid.dunn(dtw_matrix, kmeans.labels_)[0])
# for k in range(2, k_max+1):
#     agg_average = agglomerative_clustering(data, k, linkage='average')
#     silhouette.append(silhouette_score(dtw_matrix, agg_average.labels_))
#     chscore.append(symbolicDA.index_G1d(dtw_matrix, agg_average.labels_)[0])
#     dunnindex.append(clValid.dunn(dtw_matrix, agg_average.labels_)[0])
# for k in range(2, k_max+1):
#     agg_complete = agglomerative_clustering(data, k, linkage='complete')
#     silhouette.append(silhouette_score(dtw_matrix, agg_complete.labels_))
#     chscore.append(symbolicDA.index_G1d(dtw_matrix, agg_complete.labels_)[0])
#     dunnindex.append(clValid.dunn(dtw_matrix, agg_complete.labels_)[0])
# for k in range(2, k_max+1):
#     agg_single = agglomerative_clustering(data, k, linkage='single')
#     silhouette.append(silhouette_score(dtw_matrix, agg_single.labels_))
#     chscore.append(symbolicDA.index_G1d(dtw_matrix, agg_single.labels_)[0])
#     dunnindex.append(clValid.dunn(dtw_matrix, agg_single.labels_)[0])
# metrics = pd.DataFrame({'silhouette' : silhouette, 'chscore' : chscore, 'dunnindex' : dunnindex})
# metrics['algorithm'] = pd.Series(['KMeans']*9 + ['Hierarchical average']*9 + ['Hierarchical complete']*9 + ['Hierarchical single']*9)
# metrics['n_clusters'] = pd.Series([x for x in range(2,11)]*4)
# metrics = metrics[['algorithm', 'n_clusters', 'silhouette', 'chscore', 'dunnindex']]
# metrics


In [3]:
# data = [go.Scatter(x=df_test_final.columns,
#                    y=df_test_final.loc[countrycode],
#                    name=countrycode) for countrycode in df_test_final.index]

# layout = go.Layout(
#     title= ind.upper(),
#     yaxis=dict(title='Value'),
#     xaxis=dict(title='Years')
# )

# fig = go.Figure(data=data, layout=layout)
# plot(fig)

In [4]:
import plotly
import plotly.graph_objs as go 

data = pd.read_csv('data/metrics_results.csv')
# Initialize figure
def plot_series(data: pd.DataFrame) -> None:
    """AI is creating summary for plot_series

    Args:
        data (pd.DataFrame): [description]
    """
    fig = go.Figure()
    buttons = list()
    for i in range(data.shape[1]-2):
        m = data.columns[i+2,]
        df_test = data[['algorithm','n_clusters', m]]

        # transposing
        df_test_transposed = df_test.pivot_table(index='algorithm', columns=['n_clusters'], values=m).reset_index()
        df_test_final = df_test_transposed.rename_axis('').rename_axis("", axis="columns").set_index('algorithm')

        # Add Traces
        for alg in df_test_final.index:
            if i==0:
                fig.add_trace(go.Scatter(x=df_test_final.columns, y=df_test_final.loc[alg],
                        name=alg, visible=True))            
            else:
                fig.add_trace(go.Scatter(x=df_test_final.columns, y=df_test_final.loc[alg],
                        name=alg, visible=False))
        n_of_countries = df_test_final.shape[0]
        visible = [False]*n_of_countries*i + [True]*n_of_countries + [False]*n_of_countries*(n_of_countries-i-1)
        buttons.append(dict(label = m,
                    method = 'update',
                    args = [{'visible': visible},
                            {'title': m}]))    
    fig.update_layout(dict(updatemenus=[
                        # dict(
                        #     type = "buttons",
                        #     direction = "left",
                        #     buttons=list([
                        #         dict(
                        #             args=["visible", "legendonly"],
                        #             label="Deselect All",
                        #             method="restyle"
                        #         ),
                        #         dict(
                        #             args=["visible", True],
                        #             label="Select All",
                        #             method="restyle"
                        #         )
                        #     ]),
                        #     pad={"r": 10, "t": 10},
                        #     showactive=True,
                        #     x=1,
                        #     xanchor="right",
                        #     y=1.1,
                        #     yanchor="top"
                        # ),
                        dict(type='dropdown', buttons=buttons, xanchor='right', x=1, y=1.15, active=0)#, showactive=True)                    ]
    ]))
    # updatemenus = list([
    #     dict(active=-1, type='dropdown',
    #         buttons=buttons, xanchor='right', x=1, y=1.15
            
    #     )
    # ])

    
    fig.update_layout(title='Series')#, title_pad_l=40, title_xanchor='left')
    plot(fig)

In [31]:
plot_series(data)

In [5]:
import plotly.express as px
import numpy as np

def plot_dbscan(countries: pd.DataFrame, labels: np.array) -> None:
    """
    Plot cartogram presenting clustering results for given countries.

    Args:
        countries (pd.DataFrame): Pandas Dataframe containing at least one column, named 'countrycode',
        with ISO-3166 alpha-3 codes of countries
        labels (np.array): cluster assignment generated by clustering model for given countries
    """
    labels = labels.astype(str)
    countries["cluster"] = pd.Series(labels)
    fig = px.choropleth(countries, locations='countrycode', color="cluster",
                        projection='conic conformal', color_discrete_sequence=px.colors.qualitative.Pastel)
    fig.update_geos(lataxis_range=[35, 75], lonaxis_range=[-15, 45])  # customized to show Europe only
    fig.update_layout(showlegend=False, margin=dict(l=20, r=20, t=20, b=20), paper_bgcolor='rgba(0,0,0,0)')
    return fig.to_html(full_html=False, default_height=400, default_width=400)


In [2]:
from sklearn.cluster import DBSCAN
def dbscan_clustering(data: pd.DataFrame, eps: float, min_samples: int) -> DBSCAN:
    """
    Perform DBSCAN clustering.

    Args:
        data (pd.DataFrame): preprocessed dataframe with economic indexes
        eps (float): maximum distance between two points for them to be considered as neighbouring
        min_samples (int): number of samples in a neighborhood for a point to be considered as a core point

    Returns:
        DBSCAN: fitted clustering model
    """
    # transform input data into adequate structure - 3D numpy array
    data_t = data.melt(id_vars=['countrycode', 'country', 'year'])
    data_t = data_t.groupby(['countrycode', 'country', 'year', 'variable'])['value'].aggregate('mean').unstack(
        'year')
    data_t = data_t.reset_index().drop('variable', axis=1).groupby(['countrycode', 'country']).agg(list)
    n_countries = data_t.shape[0]  # number of points (countries)
    time_range = data_t.shape[1]  # time range
    n_vars = data.shape[1] - 3  # number of economic indexes
    # filling the array
    data_t_arr = np.empty(shape=(n_countries, time_range, n_vars))
    for i in range(n_countries):
        for j in range(time_range):
            data_t_arr[i][j] = np.array(data_t.iloc[i, j])
    # calculating distances between points (countries)
    dtw_matrix = dtw_ndim.distance_matrix_fast(data_t_arr, n_vars)
    # creating and fitting the model
    model = DBSCAN(eps=eps, min_samples=min_samples, metric='precomputed')
    model.fit(dtw_matrix)
    return model

In [3]:
import pandas as pd
import plotly
import numpy as np
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN

# def plot_dbscan(df, countries, labels):
data = pd.read_csv('data/data.csv')

# transform input data into adequate structure - 3D numpy array
data_t = data.melt(id_vars=['countrycode', 'country', 'year'])
data_t = data_t.groupby(['countrycode', 'country', 'year', 'variable'])['value'].aggregate('mean').unstack(
    'year')
data_t = data_t.reset_index().drop('variable', axis=1).groupby(['countrycode', 'country']).agg(list)
n_countries = data_t.shape[0]  # number of points (countries)
time_range = data_t.shape[1]  # time range
n_vars = data.shape[1] - 3  # number of economic indexes
# filling the array
data_t_arr = np.empty(shape=(n_countries, time_range, n_vars))
for i in range(n_countries):
    for j in range(time_range):
        data_t_arr[i][j] = np.array(data_t.iloc[i, j])
# calculating distances between points (countries)
dtw_matrix = dtw_ndim.distance_matrix_fast(data_t_arr, n_vars)

# labels = labels.astype(str)
# countries["cluster"] = pd.Series(labels)
# data = [dict(type='choropleth',
#             locations = countries['countrycode'].astype(str),
#             color=countries['cluster'].astype(int),
#             projection='conic conformal', color_discrete_sequence=px.colors.qualitative.Pastel)]
countries = data[['countrycode','country']].drop_duplicates().reset_index(drop=True)
# let's create some additional, random data 

##### WYKRES ######
eps_grid = [3, 3.1, 3.2, 3.3, 3.4, 3.5]
min_samples_grid = [2,3,4,5,6]
plot_data = []
for eps in eps_grid:
    for min_samples in min_samples_grid:
        model = DBSCAN(eps=eps, min_samples=min_samples, metric='precomputed')
        model.fit(dtw_matrix)
        plot_data.append(dict(type='choropleth',
                locations = countries['countrycode'].astype(str),
                z=model.labels_))
# (3,2), (3,3) ... (3.1, 2), (3.1, 3) 

# let's create the steps for the slider
# eps
steps = []
i=0
for eps in eps_grid:
    for min_samples in min_samples_grid:
        step = dict(method='restyle',
                    args=['visible', [False] * len(plot_data)],
                    label='{} / {}'.format(eps, min_samples))
        step['args'][1][i] = True
        steps.append(step)
        i+=1
# min_samples
# steps2 = []
# for i in range(len(plot_data)):
#     step = dict(method='restyle',
#                 args=['visible', [False] * len(plot_data)],
#                 label='Eps2 {}'.format(3+ i/10))
#     step['args'][1][i] = True
#     steps2.append(step)

sliders = [dict(active=0,
                pad={"t": 1},
                steps=steps,
                currentvalue={'prefix':'Eps - ',
                'suffix':' - min samples'})]
                # dict(active=0,
                # pad={"t": 1},
                # steps=steps2)]    
layout = dict(geo=dict(projection={'type': 'conic conformal'}, lataxis={'range':[35,75]}, 
 lonaxis={'range' : [-15, 45]}),
            sliders=sliders)

fig = dict(data=plot_data, 
        layout=layout)
#fig.update_layout(showlegend=False)


In [38]:
# def plot_dbscan(df, countries, labels):
data = pd.read_csv('data/data.csv')

year_grid = [x for x in range(1999,2020,1)]
plot_data = []
for year in year_grid:
        model = DBSCAN(eps=eps, min_samples=min_samples, metric='precomputed')
        model.fit(dtw_matrix)
        plot_data.append(dict(type='choropleth',
                locations = countries['countrycode'].astype(str),
                z=model.labels_))
# transform input data into adequate structure - 3D numpy array
data_t = data.melt(id_vars=['countrycode', 'country', 'year'])
data_t = data_t.groupby(['countrycode', 'country', 'year', 'variable'])['value'].aggregate('mean').unstack(
    'year')
data_t = data_t.reset_index().drop('variable', axis=1).groupby(['countrycode', 'country']).agg(list)
n_countries = data_t.shape[0]  # number of points (countries)
time_range = data_t.shape[1]  # time range
n_vars = data.shape[1] - 3  # number of economic indexes
# filling the array
data_t_arr = np.empty(shape=(n_countries, time_range, n_vars))
for i in range(n_countries):
    for j in range(time_range):
        data_t_arr[i][j] = np.array(data_t.iloc[i, j])
# calculating distances between points (countries)
dtw_matrix = dtw_ndim.distance_matrix_fast(data_t_arr, n_vars)

# labels = labels.astype(str)
# countries["cluster"] = pd.Series(labels)
# data = [dict(type='choropleth',
#             locations = countries['countrycode'].astype(str),
#             color=countries['cluster'].astype(int),
#             projection='conic conformal', color_discrete_sequence=px.colors.qualitative.Pastel)]
countries = data[['countrycode','country']].drop_duplicates().reset_index(drop=True)
# let's create some additional, random data 

##### WYKRES ######
eps_grid = [3, 3.1, 3.2, 3.3, 3.4, 3.5]
min_samples_grid = [2,3,4,5,6]
plot_data = []
for eps in eps_grid:
    for min_samples in min_samples_grid:
        model = DBSCAN(eps=eps, min_samples=min_samples, metric='precomputed')
        model.fit(dtw_matrix)
        plot_data.append(dict(type='choropleth',
                locations = countries['countrycode'].astype(str),
                z=model.labels_))
# (3,2), (3,3) ... (3.1, 2), (3.1, 3) 

# let's create the steps for the slider
# eps
steps = []
i=0
for eps in eps_grid:
    for min_samples in min_samples_grid:
        step = dict(method='restyle',
                    args=['visible', [False] * len(plot_data)],
                    label='{} / {}'.format(eps, min_samples))
        step['args'][1][i] = True
        steps.append(step)
        i+=1
# min_samples
# steps2 = []
# for i in range(len(plot_data)):
#     step = dict(method='restyle',
#                 args=['visible', [False] * len(plot_data)],
#                 label='Eps2 {}'.format(3+ i/10))
#     step['args'][1][i] = True
#     steps2.append(step)

sliders = [dict(active=0,
                pad={"t": 1},
                steps=steps,
                currentvalue={'prefix':'Eps - ',
                'suffix':' - min samples'})]
                # dict(active=0,
                # pad={"t": 1},
                # steps=steps2)]    
layout = dict(geo=dict(projection={'type': 'conic conformal'}, lataxis={'range':[35,75]}, 
 lonaxis={'range' : [-15, 45]}),
            sliders=sliders)

fig = dict(data=plot_data, 
        layout=layout)
#fig.update_layout(showlegend=False)


In [6]:
def kmeans_clustering(data: pd.DataFrame, n_clusters: int) -> TimeSeriesKMeans:
    """
    Perform KMeans clustering.

    Args:
        data (pd.DataFrame): preprocessed dataframe with economic indexes
        n_clusters (int): number of clusters to be formed

    Returns:
        TimeSeriesKMeans: fitted clustering model
    """
    # transform input data into adequate structure - 3D numpy array
    data_agg = data.drop('year', axis=1).groupby(['countrycode', 'country']).agg(list)
    n_countries = data_agg.shape[0] # number of points (countries)
    time_range =  len(data['year'].drop_duplicates()) # time range
    n_vars = data.shape[1] - 3 # number of economic indexes
    # filling the array
    data_agg_arr = np.empty(shape=(n_countries, n_vars, time_range))
    for i in range(data_agg.shape[0]):
        for j in range(data_agg.shape[1]):
            data_agg_arr[i][j] = np.array(data_agg.iloc[i,j])
    # creating and fitting a model
    model = TimeSeriesKMeans(n_clusters=n_clusters, metric='dtw', random_state=123)
    model.fit(data_agg_arr)
    return model


In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from tslearn.preprocessing import TimeSeriesScalerMeanVariance
from tslearn.clustering import TimeSeriesKMeans
from dtaidistance import dtw_ndim
from scipy.cluster.hierarchy import dendrogram
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score

def agglomerative_clustering(data: pd.DataFrame, n_clusters: int, linkage: str) -> AgglomerativeClustering:
    """
    Perform hierarchical clustering.

    Args:
        data (pd.DataFrame): preprocessed dataframe with economic indexes
        n_clusters (int): number of clusters to be formed
        linkage (str): type of linkage criterion; 'average', 'complete' or 'single'

    Returns:
        AgglomerativeClustering: fitted clustering model
    """
    # transform input data into adequate structure - 3D numpy array
    data_t = data.melt(id_vars=['countrycode','country','year'])
    data_t = data_t.groupby(['countrycode','country','year','variable'])['value'].aggregate('mean').unstack('year')
    data_t = data_t.reset_index().drop('variable', axis=1).groupby(['countrycode', 'country']).agg(list)
    n_countries = data_t.shape[0] # number of points (countries)
    time_range =  data_t.shape[1] # time range
    n_vars = data.shape[1] - 3 # number of economic indexes
    # filling the array
    data_t_arr = np.empty(shape=(n_countries, time_range, n_vars))
    for i in range(n_countries):
        for j in range(time_range):
            data_t_arr[i][j] = np.array(data_t.iloc[i,j])
    # calculating distances between points (countries)
    dtw_matrix = dtw_ndim.distance_matrix_fast(data_t_arr, n_vars)
    print(dtw_matrix)
    # creating and fitting the model
    model = AgglomerativeClustering(
        n_clusters=n_clusters, affinity='precomputed', linkage=linkage, compute_distances=True)
    model.fit(dtw_matrix)
    return model


In [28]:
np.where(np.isnan(dtw_matrix))

(array([], dtype=int64), array([], dtype=int64))

In [18]:
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import plot
data = pd.read_csv('data/data.csv')

year_grid = [x for x in range(1999,2020,1)]
plot_data = []
steps = []
countries = data[['countrycode','country']].drop_duplicates().reset_index(drop=True)
i=0
for y in year_grid:
    data_trimmed = data.loc[data.year <= y,:].loc[data.year > y-10, :]
    print(data_trimmed.year.unique())
    model = agglomerative_clustering(data_trimmed, 4, 'complete')
    plot_data.append(dict(type='choropleth',
        locations = countries['countrycode'].astype(str),
        z=model.labels_))
    # plot_data.append(dict(type='choroplethmapbox', marker_opacity=0.8,
    #     locations = countries['countrycode'].astype(str), below="",
    #     z=['black']*len(year_grid)))
    step = dict(method='restyle',
                args=['visible', [False] * len(year_grid)],
                label='{}'.format(y))
    step['args'][1][i] = True
    steps.append(step)
    # step = dict(method='restyle',
    #             args=['visible', [False] * len(year_grid)],
    #             label='{}'.format(y))
    # step['args'][1][i] = True
    # steps.append(step)
    i+=1

sliders = [dict(active=0,
                pad={"t": 1},
                steps=steps)]
                # dict(active=0,
                # pad={"t": 1},
                # steps=steps2)]    
layout = dict(geo=dict(projection={'type': 'conic conformal'}, lataxis={'range':[35,75]}, 
 lonaxis={'range' : [-15, 45]}),
            sliders=sliders, showlegend=False)

fig = dict(data=plot_data, 
        layout=layout)
plot(fig)

[1990 1991 1992 1993 1994 1995 1996 1997 1998 1999]
[[0.         6.07505746 7.10185172 ... 5.72016906 6.34470675 4.73083944]
 [6.07505746 0.         2.60780994 ... 2.02561094 1.86659901 3.26827653]
 [7.10185172 2.60780994 0.         ... 3.65636985 1.99767049 4.35202898]
 ...
 [5.72016906 2.02561094 3.65636985 ... 0.         3.32891458 3.14421664]
 [6.34470675 1.86659901 1.99767049 ... 3.32891458 0.         3.57331399]
 [4.73083944 3.26827653 4.35202898 ... 3.14421664 3.57331399 0.        ]]
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000]
[[0.         6.03530019 7.07746197 ... 5.71294466 6.31076537 4.65937552]
 [6.03530019 0.         2.62506765 ... 1.94953029 1.85905104 3.29433937]
 [7.07746197 2.62506765 0.         ... 3.65308631 1.9733552  4.38178437]
 ...
 [5.71294466 1.94953029 3.65308631 ... 0.         3.27609072 3.12379756]
 [6.31076537 1.85905104 1.9733552  ... 3.27609072 0.         3.61526361]
 [4.65937552 3.29433937 4.38178437 ... 3.12379756 3.61526361 0.        ]]
[1992 19

'temp-plot.html'

In [ ]:
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import plot
data = pd.read_csv('data/data.csv')
labels = [0,1,2]*13
data_2019 = data[data.year == 2019]
data_2019.loc[:, 'Cluster'] = pd.Series(labels)
data_2019.groupby('Cluster').agg('mean')[['pop', 'rgdpna_per_cap', 'net_migration', 'hdi']].reset_index()

c:\Users\agama\Documents\BEngThesis\django\bengthesis\lib\site-packages\pandas\core\indexing.py:1667: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



Cluster       pop  rgdpna_per_cap  net_migration       hdi
0      2.0  0.017745        0.112512       0.205896  0.517123